import { useEffect, useState } from 'react';
import { api } from '../api.js';
import { ErrorBox, Money, Spinner, Toggle } from '../components.jsx';

export function OwnerPanel() {
  const [tab, setTab] = useState('configuration'); const [config, setConfig] = useState(null); const [leads, setLeads] = useState([]);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [failure, setFailure] = useState('');
  const load = () => { setFailure(''); Promise.all([api.adminConfig(), api.leads()]).then(([c, l]) => { setConfig(c); setLeads(l); }).catch(e => setFailure(e.message)); };
  useEffect(load, []);
  const mutate = fn => setConfig(current => { const next = structuredClone(current); fn(next); return next; });
  const save = async () => { setBusy(true); setFailure(''); try { const result = await api.saveConfig(config); setConfig({ ...result.config, is_draft: true }); setMessage(result.message); } catch (e) { setFailure(e.message); } finally { setBusy(false); } };
  const publish = async () => { setBusy(true); setFailure(''); try { const result = await api.publish(); setConfig({ ...result.config, is_draft: false }); setMessage(result.message); } catch (e) { setFailure(e.message); } finally { setBusy(false); } };
  return <div className="owner-page"><aside><a className="owner-brand" href="/owner"><span className="brand-mark">N</span><b>Northline Roofing<br />& Exteriors</b></a><nav><button className={tab === 'configuration' ? 'active' : ''} onClick={() => setTab('configuration')}>Configuration</button><button className={tab === 'leads' ? 'active' : ''} onClick={() => setTab('leads')}>Leads <span>{leads.length}</span></button></nav><a href="/">View public estimator ↗</a></aside>
    <main className="owner-main"><header><div><p>Owner panel</p><h1>{tab === 'configuration' ? 'Estimator configuration' : 'Captured leads'}</h1></div>{tab === 'configuration' ? <div className="owner-actions"><button className="secondary" disabled={busy} onClick={save}>{busy ? 'Saving…' : 'Save draft'}</button><button className="primary" disabled={busy || !config?.is_draft} onClick={publish}>Publish changes</button></div> : null}</header>
    {failure ? <ErrorBox retry={load}>{failure}</ErrorBox> : null}{message ? <div className="alert info" role="status">{message}</div> : null}
    {!config ? <Spinner /> : tab === 'configuration' ? <ConfigEditor config={config} mutate={mutate} /> : <Leads leads={leads} config={config} />}</main></div>;
}

function ConfigEditor({ config, mutate }) { return <div className="editor">
  <div className="publish-note"><b>{config.is_draft ? `Draft version ${config.config_version}` : `Live version ${config.config_version}`}</b><span>Save as a draft while you work. Nothing changes for homeowners until you publish.</span></div>
  <section><div className="section-heading"><div><h2>Questions</h2><p>Edit homeowner-facing wording or temporarily hide a question.</p></div></div>
    {config.questions.map((q, qi) => <div className="question-row" key={q.key}><div className="question-fields"><label className="field"><span>Question label</span><input value={q.label} onChange={e => mutate(c => { c.questions[qi].label = e.target.value; })} /></label><Toggle checked={q.active} label={q.active ? 'Shown' : 'Hidden'} onChange={value => mutate(c => { c.questions[qi].active = value; })} /></div>
      {q.options ? <><div className="rate-list">{q.options.map((option, oi) => { const priceKey = ['rate_per_sqft', 'multiplier', 'tear_off_per_sqft'].find(key => key in option); return <div className="rate-row" key={option.value}><input aria-label="Option label" value={option.label} onChange={e => mutate(c => { c.questions[qi].options[oi].label = e.target.value; })} />{priceKey ? <label><span>{priceKey === 'multiplier' ? 'Multiplier' : priceKey === 'rate_per_sqft' ? '$ / sq ft' : 'Tear-off $ / sq ft'}</span><input type="number" step="0.01" value={option[priceKey]} onChange={e => mutate(c => { c.questions[qi].options[oi][priceKey] = Number(e.target.value); })} /></label> : null}</div>; })}</div>{!q.active ? <label className="inactive-default">Used while hidden<select value={q.inactive_default} onChange={e => mutate(c => { c.questions[qi].inactive_default = e.target.value; })}>{q.options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label> : null}</> : <><div className="bounds"><label>Minimum<input type="number" value={q.min} onChange={e => mutate(c => { c.questions[qi].min = Number(e.target.value); })} /></label><label>Maximum<input type="number" value={q.max} onChange={e => mutate(c => { c.questions[qi].max = Number(e.target.value); })} /></label></div>{!q.active ? <label className="inactive-default">Used while hidden<input type="number" value={q.inactive_default} onChange={e => mutate(c => { c.questions[qi].inactive_default = Number(e.target.value); })} /></label> : null}</>}
    </div>)}
  </section>
  <section><div className="section-heading"><div><h2>Estimate modifiers</h2><p>These values affect every new estimate after publishing.</p></div></div><div className="modifier-grid">{Object.entries(config.modifiers).map(([key, value]) => <label key={key}><span>{({ waste_factor: 'Waste factor', permit_flat_fee: 'Permit flat fee', range_spread_pct: 'Range spread' })[key]}</span><input type="number" step="0.01" value={value} onChange={e => mutate(c => { c.modifiers[key] = Number(e.target.value); })} /><small>{key === 'waste_factor' ? 'Decimal (0.10 = 10%)' : key === 'permit_flat_fee' ? 'US dollars' : 'Percent'}</small></label>)}</div></section>
  </div>; }

function Leads({ leads, config }) { const labels = new Map(config.questions.flatMap(q => q.options?.map(o => [o.value, o.label]) || [])); return <section className="leads-section"><div className="table-wrap"><table><thead><tr><th>Homeowner</th><th>Contact</th><th>Project</th><th>Estimate</th><th>Captured</th></tr></thead><tbody>{leads.map(lead => <tr key={lead.id}><td><b>{lead.name}</b><small>Config v{lead.config_version}</small></td><td><a href={`tel:${lead.phone}`}>{lead.phone}</a><a href={`mailto:${lead.email}`}>{lead.email}</a></td><td>{lead.answers.roof_area ? `${Number(lead.answers.roof_area).toLocaleString()} sq ft` : 'Historical lead'}<small>{labels.get(lead.answers.material) || lead.answers.material || '—'}</small></td><td><b><Money value={lead.estimate_low} /> – <Money value={lead.estimate_high} /></b></td><td>{new Date(lead.captured_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</td></tr>)}</tbody></table></div></section>; }
